# Generated by Django 4.2.16 on 2024-10-10 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0007_remove_rab_mou_nda_alter_attachment_mou_nda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proposal')),
                ('mou_nda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_mou', related_query_name='proposal_mou', to='api.mou_nda')),
                ('pks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_pks', related_query_name='proposal_pks', to='api.pks')),
            ],
        ),
    ]
