# Generated by Django 4.2.16 on 2024-10-03 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mou_nda',
            name='official_undersign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.functionary'),
        ),
        migrations.AddField(
            model_name='pks',
            name='official_undersign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.functionary'),
        ),
    ]
