# Generated by Django 4.2.16 on 2024-10-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mou_nda_official_undersign_pks_official_undersign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pks',
            name='mou_nda_number',
        ),
        migrations.AddField(
            model_name='pks',
            name='pks_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mou_nda',
            name='approval_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mou_nda',
            name='mou_nda_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mou_nda',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mou_nda',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'pengajuan'), ('r', 'revisi'), ('t', 'ditolak'), ('m', 'manajer'), ('v', 'vp'), ('d1', 'direksi'), ('mk', 'manager_kemitraan'), ('sk', 'staff_kemitraan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pks',
            name='approval_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pks',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pks',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'pengajuan'), ('r', 'revisi'), ('t', 'ditolak'), ('m', 'manajer'), ('v', 'vp'), ('d1', 'direksi'), ('mk', 'manager_kemitraan'), ('sk', 'staff_kemitraan')], max_length=20),
        ),
    ]
