# Generated by Django 4.2.16 on 2024-10-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_pks_mou_nda_number_pks_pks_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mou_nda',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'pengajuan'), ('r', 'revisi'), ('t', 'ditolak'), ('m', 'manajer'), ('v', 'vp'), ('d1', 'direksi'), ('mk', 'manager_kemitraan'), ('sk', 'staff_kemitraan')], default='d', max_length=20),
        ),
        migrations.AlterField(
            model_name='pks',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'pengajuan'), ('r', 'revisi'), ('t', 'ditolak'), ('m', 'manajer'), ('v', 'vp'), ('d1', 'direksi'), ('mk', 'manager_kemitraan'), ('sk', 'staff_kemitraan')], default='d', max_length=20),
        ),
    ]
