# Generated by Django 4.2.16 on 2024-10-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_mou_nda_status_alter_pks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mou_nda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', related_query_name='attachments', to='api.mou_nda'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='mou_nda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', related_query_name='scopes', to='api.mou_nda'),
        ),
    ]
