# Generated by Django 4.2.16 on 2024-10-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mou_nda_position_level_pks_position_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rab',
            name='mou_nda',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mou_nda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments_mou', related_query_name='attachments_mou', to='api.mou_nda'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='pks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments_pks', related_query_name='attachments_pks', to='api.pks'),
        ),
        migrations.AlterField(
            model_name='mou_nda',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'pengajuan'), ('r', 'revisi'), ('t', 'ditolak'), ('m', 'manajer'), ('v', 'vp'), ('d1', 'direksi'), ('mk', 'manager_kemitraan'), ('sk', 'staff_kemitraan'), ('f', 'Selesai')], default='d', max_length=20),
        ),
        migrations.AlterField(
            model_name='pks',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'pengajuan'), ('r', 'revisi'), ('t', 'ditolak'), ('m', 'manajer'), ('v', 'vp'), ('d1', 'direksi'), ('mk', 'manager_kemitraan'), ('sk', 'staff_kemitraan'), ('f', 'Selesai')], default='d', max_length=20),
        ),
        migrations.AlterField(
            model_name='rab',
            name='pks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rab', related_query_name='rab', to='api.pks'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='mou_nda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes_mou', related_query_name='scopes_mou', to='api.mou_nda'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='pks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes_pks', related_query_name='scopes_pks', to='api.pks'),
        ),
    ]
