# Generated by Django 4.2.16 on 2024-10-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_rab_mou_nda_alter_attachment_mou_nda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mou_nda',
            name='is_stop_clock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pks',
            name='is_stop_clock',
            field=models.BooleanField(default=False),
        ),
    ]
