# Generated by Django 4.2.16 on 2024-10-11 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mou_nda_is_stop_clock_pks_is_stop_clock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mou_nda',
            name='position_level',
            field=models.IntegerField(default=1, max_length=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mou_nda',
            name='status',
            field=models.CharField(choices=[('p', 'pengajuan'), ('r', 'revisi'), ('t', 'ditolak'), ('m', 'manajer'), ('v', 'vp'), ('d1', 'direksi'), ('mk', 'manager_kemitraan'), ('sk', 'staff_kemitraan'), ('f', 'Selesai')], default='d', max_length=20),
        ),
        migrations.AlterField(
            model_name='pks',
            name='position_level',
            field=models.IntegerField(default=1, max_length=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pks',
            name='status',
            field=models.CharField(choices=[('p', 'pengajuan'), ('r', 'revisi'), ('t', 'ditolak'), ('m', 'manajer'), ('v', 'vp'), ('d1', 'direksi'), ('mk', 'manager_kemitraan'), ('sk', 'staff_kemitraan'), ('f', 'Selesai')], default='d', max_length=20),
        ),
    ]
